Add specification on top-nav
Dindihub/docsy-starter pull request #23
Opened 2024-08-24 14:30 UTC by Dindihub

This PR covers issue #18 

 Moved specification on top-nav following a recommendation on the [TUF documentation analysis](https://github.com/cncf/techdocs/tree/main/analyses/0012-TUF)

2024-08-27 00:23 UTC, chalin reviewed
Now that I'm seeing this, I think that we can rework (simplify) this. See inline comments.

2024-08-27 00:23 UTC, chalin commented on content/en/specifications/specification-index.md
Drop this page

2024-08-27 00:23 UTC, chalin commented on content/en/specifications/specification-latest.md
> +The following doc versions are available:
```suggestion
The following specification versions are available:
```

2024-08-27 00:23 UTC, chalin commented on content/en/specifications/specification-latest.md
> +[spec versions](https://theupdateframework.github.io/specification/)
Eventually we might not need the link to the GH pages site, but for now I'd like to keep it. Let's adjust the prose though:

```suggestion
This list is also available from
[Spec versions](https://theupdateframework.github.io/specification/).
```

2024-08-27 06:30 UTC, Dindihub commented
This is ready for another review @chalin

2024-08-27 09:09 UTC, lukpueh requested changes
The text reads like a general TUF project overview, and only vaguely prepares the reader for the specification. 

I suggest to remove it and just leave the index. Or add a small paragraph about what the user will find in the spec. Maybe you can take inspiration from [this talk](https://youtu.be/1rM8a9cPo-I?t=1107). More specifically, about how the spec defines a detailed client updater workflow and otherwise TUF repo primitives (roles, metadata, delegations), which can be used as building blocks.

2024-08-27 09:57 UTC, Dindihub commented
> The text reads like a general TUF project overview, and only vaguely prepares the reader for the specification.
> 
> I suggest to remove it and just leave the index. Or add a small paragraph about what the user will find in the spec. Maybe you can take inspiration from [this talk](https://youtu.be/1rM8a9cPo-I?t=1107). More specifically, about how the spec defines a detailed client updater workflow and otherwise TUF repo primitives (roles, metadata, delegations), which can be used as building blocks.

@lukpueh Okay. I'll try. Thanks

2024-08-27 10:58 UTC, Dindihub commented
@lukpueh I have edited the section and added in the video you shared for reference. Let me know what you think.

2024-08-27 21:54 UTC, chalin reviewed
@lukpueh and I seem to have the same idea of having a single page (in fact, that is what I tried to convey in my round of comments from earlier).

Please make the changes suggested in the comments of this review.

2024-08-27 21:54 UTC, chalin commented on content/en/specifications/specification-latest.md
Drop this page. Move the content to the "main" (i.e., only) specification page.

2024-08-27 21:54 UTC, chalin commented on content/en/specifications/_index.md
Rename this file to `content/en/specs.md`, which means eliminating the folder, and merging the version list into this new page.

2024-08-27 21:54 UTC, chalin commented on content/en/specifications/_index.md
> +linkTitle: Specification
```suggestion
```

2024-08-27 21:54 UTC, chalin commented on content/en/specifications/_index.md
> +with various software update systems.
I'm not sure that I can make sense of this paragraph. I'd suggest replacing it quite simply by the list of specification versions:

```suggestion
The following specification versions are available:

- [latest](https://theupdateframework.github.io/specification/latest/index.html)
- [draft](https://theupdateframework.github.io/specification/draft/index.html)
- [v1.0.33](https://theupdateframework.github.io/specification/v1.0.33/index.html)
- [v1.0.32](https://theupdateframework.github.io/specification/v1.0.32/index.html)
- [v1.0.31](https://theupdateframework.github.io/specification/v1.0.31/index.html)
- [v1.0.30](https://theupdateframework.github.io/specification/v1.0.30/index.html)
- [v1.0.29](https://theupdateframework.github.io/specification/v1.0.29/index.html)
- [v1.0.28](https://theupdateframework.github.io/specification/v1.0.28/index.html)
- [v1.0.27](https://theupdateframework.github.io/specification/v1.0.27/index.html)
- [v1.0.26](https://theupdateframework.github.io/specification/v1.0.26/index.html)
- [v1.0.25](https://theupdateframework.github.io/specification/v1.0.25/index.html)
- [v1.0.24](https://theupdateframework.github.io/specification/v1.0.24/index.html)
- [v1.0.23](https://theupdateframework.github.io/specification/v1.0.23/index.html)
- [v1.0.22](https://theupdateframework.github.io/specification/v1.0.22/index.html)
- [v1.0.20](https://theupdateframework.github.io/specification/v1.0.20/index.html)
- [v1.0.19](https://theupdateframework.github.io/specification/v1.0.19/index.html)
- [v1.0.18](https://theupdateframework.github.io/specification/v1.0.18/index.html)
- [v1.0.17](https://theupdateframework.github.io/specification/v1.0.17/index.html)

This list is also available from
[Spec versions](https://theupdateframework.github.io/specification/).
```

2024-08-27 21:54 UTC, chalin commented on content/en/specifications/_index.md
> +or watch the following video.
```suggestion
To learn more, see the latest version of the
[specification](https://theupdateframework.github.io/specification/latest/),
or watch the following video.
```

2024-08-28 15:12 UTC, lukpueh approved these changes

2024-08-28 18:04 UTC, chalin approved these changes
LGTM.

There will be followup improvements to make (e.g., possibly not using `type: docs` or maybe hiding the left nav, but that can be done later.

2024-08-28 18:04 UTC, merged